name: ci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unset ANDROID_HOME
        run: echo "ANDROID_HOME=" >> $GITHUB_ENV
      - name: Setup Fluent CI CLI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: bun
          args: install
      - name: Run gradle assemble
        run: fluentci run --wasm android assemble_release
        working-directory: android